server:
  port: 8080
spring:
  application:
    name: short-url-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #password: tiantang
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: short-url-db
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



